apiVersion: v1
kind: Namespace
metadata:
  name: uat

---

kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    app: copa
  name: copa
  namespace: uat
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: copa
  template:
    metadata:
      labels:
        app: copa
    spec:
      containers:
        - name: copa-funtime
          image: copa:20221029.3
          imagePullPolicy: Never

---

kind: Service
apiVersion: v1
metadata:
  labels:
    app: copa
  name: copa-service
  namespace: uat
spec:
  ports:
    - port: 80
  selector:
    app: copa

